language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install pytest-pep8
  - pip install .
  - pip install pytest-cov python-coveralls
  - pip install -r requirements.txt
script:
    py.test --pep8 -vv --cov
after_success:
    coveralls
